import type { Metadata } from "next";
import { Playpen_Sans } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import AuthProvider from "@/app/redux/auth/AuthProvider";

const playpenSans = Playpen_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "XPedia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={playpenSans.className}>{children}</body>
      </AuthProvider>
    </html>
  );
}
